version: "3.9"

services:
  db:
    image: postgres:13.3
    container_name: tt_serasa_postgres
    environment:
      - POSTGRES_DB=tt_serasa
      - POSTGRES_USER=serasa
      - POSTGRES_PASSWORD=serasa_psql
    ports:
      - 5432:5432
    volumes:
      - ./.db/data/postgres:/var/lib/postgresql/data
#  server:
#    container_name: tt_serasa_golang_server
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    depends_on:
#      - db
#    ports:
#      - 8008:8008
#      - 8009:8009
#      - 8010:8010
