// Code generated by sqlc. DO NOT EDIT.

package negativations

import (
	"context"
)

type Querier interface {
	DeleteNegativated(ctx context.Context, id int64) error
	GetNegativatedByID(ctx context.Context, id int64) (Negativations, error)
	ListNegativated(ctx context.Context, arg ListNegativatedParams) ([]Negativations, error)
	Negativate(ctx context.Context, arg NegativateParams) (Negativations, error)
	UpdateNegativated(ctx context.Context, arg UpdateNegativatedParams) (Negativations, error)
}

var _ Querier = (*Queries)(nil)
