name: TT-SERASA_GOLANG_NegativationAPI CI jobs

on:
  push:
    branches: *
  pull_request:
    branches: *

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:

      - name: Setup Golang 1.16.4
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.4
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: make test
